name: 'PR Conversation Action'
description: 'Adds a default conversation to new pull requests'
author: 'Aaron Ford'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
